### ISSUE TITLE
python-flake8-import-order bugs not being filed

### ISSUE THREAD

**Issue by scop** [release-monitoring/anitya#432]
I've noticed that python-flake8-import-order bugs are not being filed in RH bugzilla for Fedora, even though release-monitoring.org shows the correct versions, the project is mapped there for Fedora, and bugs enabled in Fedora pkgdb. I think the system failed to file a bug for release 0.11 some time ago, and now it apparently failed again for release 0.12.

**Comment by jeremycline** [comment]
Interesting. Several people have noticed that [the-new-hotness](https://github.com/fedora-infra/the-new-hotness) in production has missed new releases. Anitya [definitely published the fedmsg](https://apps.fedoraproject.org/datagrepper/raw?topic=org.release-monitoring.prod.anitya.project.version.update&package=python-flake8-import-order) for both 0.11 and 0.12.

There's currently a new version of the-new-hotness in staging and it [did file a bug for python-flake8-import-order-0.12](https://partner-bugzilla.redhat.com/show_bug.cgi?id=1394385). I'm about to deploy the new version in production, but I'll also poke around the logs to see if I can see what happened.

**Comment by jeremycline** [comment]
Okay, I figured it out. Production the-new-hotness got the notification, but dropped it because it thought the package wasn't in rawhide:
```
[2017-02-11 12:18:41][    fedmsg WARNING] No rawhide version found for u'python-flake8-import-order'
[2017-02-11 12:18:41][    fedmsg    INFO] publishing topic 'update.drop'
```

This was a bug in the-new-hotness (https://github.com/fedora-infra/the-new-hotness/issues/127) that @ignatenkobrain fixed. It seems that it's much more reliable since staging didn't have a problem with this! \o/

I'm going to close this since it's a the-new-hotness bug, and it should be fixed. Thanks for the report!
