### ISSUE TITLE
Fedora bug not being created

### ISSUE THREAD

**Issue by swt2c** [release-monitoring/anitya#436]
Can you please check:
https://release-monitoring.org/project/5418/

It shows the latest version (correctly) of poco at 1.7.7 while Fedora has 1.7.3.  However, it hasn't created a Fedora bug about this.

**Comment by jeremycline** [comment]
I believe this was due to a bug in the-new-hotness that has been fixed and deployed to production as of last week. [Anitya published the new version message](https://apps.fedoraproject.org/datagrepper/raw?topic=org.release-monitoring.prod.anitya.project.version.update&package=poco) and [the-new-hotness saw it](https://apps.fedoraproject.org/datagrepper/id?id=2016-bfeeb153-40e7-4303-97ac-f57fccbbb4f2&is_raw=true&size=extra-large), but did not find the version in rawhide.

the-new-hotness now uses [mdapi](https://github.com/fedora-infra/the-new-hotness/issues/127) which should be much more reliable. Sorry about the inconvenience!
