### ISSUE TITLE
Anitya notified me about a new version of cswrap now despite it was already built a week ago

### ISSUE THREAD

**Issue by kdudka** [release-monitoring/anitya#439]
Anitya notified me (as Fedora maintainer) about a new version of cswrap now despite it was already built for Fedora more than a week ago.  Same issue with cscppc, csdiff and csmock:

https://release-monitoring.org/project/13349/
https://release-monitoring.org/project/13350/
https://release-monitoring.org/project/13351/
https://release-monitoring.org/project/13352/

**Comment by kdudka** [comment]
Same problem with nss-pem.  On March 4th I got notification:

```A new version of "nss-pem" has been detected: "nss-pem-1.0.3" newer than "nss-pem-1.0.2", packaged as "nss-pem"```

... despite ```nss-pem-1.0.3-1.fc2{4,5,6,7}``` was already built on March 1st.

**Comment by jeremycline** [comment]
Okay, so it looks like Anitya didn't see the new version of nss-pem [until the 4th](https://apps.fedoraproject.org/datagrepper/id?id=2017-53d170ed-abae-4197-8e53-9511ee998deb&is_raw=true&size=extra-large), possibly because it only scans projects every 12 hours and the first few times maybe there were network issues? 

In any case, it doesn't look like the-new-hotness (which determines whether or not the package needs to be updated in Fedora) filed a bug or anything. I think you can stop getting these emails by tweaking your [FMN filters](https://apps.fedoraproject.org/notifications/) to not include messages from Anitya about packages you maintain.

**Comment by kdudka** [comment]
On Monday, March 06, 2017 06:50:56 Jeremy Cline wrote:
> Okay, so it looks like Anitya didn't see the new version of nss-pem [until
> the
> 4th](https://apps.fedoraproject.org/datagrepper/id?id=2017-53d170ed-abae-41
> 97-8e53-9511ee998deb&is_raw=true&size=extra-large), possibly because it only
> scans projects every 12 hours and the first few times maybe there were
> network issues?

It is not about the precise period really.  I do not care if the status is 
checked each 12 minutes or each 12 hours.  The bug here is that it sends 
notification based on outdated data.  If up2date data cannot be retrieved
for any reason (Network issues, Github issues, Koji issues, whatever), the 
notification should simply not be sent.

**Comment by jeremycline** [comment]
> It is not about the precise period really. I do not care if the status is checked each 12 minutes or each 12 hours. The bug here is that it sends notification based on outdated data. If up2date data cannot be retrieved for any reason (Network issues, Github issues, Koji issues, whatever), the notification should simply not be sent.

I was simply hypothesizing why it took several days to find the update.

Anitya doesn't know what versions are in downstream releases (Fedora, Debian, Arch, Gentoo, etc.). It simply sees a newer version than it previously knew about and emits a message. We'd have to know about what version of a project is in every distribution package that project is mapped to, and even then what would we do when (for example) Fedora has the new version and Debian doesn't? It would still make sense to emit a message.

We _could_ add some smarts to the Fedora notification system to take that message and check if the package is already in Rawhide. That would probably go in the [fmn](https://github.com/fedora-infra/fmn) project. However, that doesn't make much sense because the whole point of [the-new-hotness](https://github.com/fedora-infra/the-new-hotness/) is to file bugs against projects that are updated upstream, but aren't yet updated in Rawhide. It's (correctly) not filing bugs against the packages you've listed. Just configure your notification settings to not send you messages about Anitya-emitted messages.

**Comment by kdudka** [comment]
Then the notification message is confusing:

```
A new version of "nss-pem" has been detected: "nss-pem-1.0.3" newer than "nss-pem-1.0.2",
packaged as "nss-pem"
```

I thought it was telling me that upstream has ```1.0.3``` whereas the latest packaged version (in Fedora) is ```1.0.2```.

**Comment by kdudka** [comment]
Attached: [anitya-issue-439.mbox.zip](https://github.com/release-monitoring/anitya/files/824476/anitya-issue-439.mbox.zip)
