### ISSUE TITLE
Add REST API v2 documentation

### ISSUE THREAD

**Issue by ncoghlan** [release-monitoring/anitya#464]
https://github.com/release-monitoring/anitya/pull/401 added a new Flask-RESTful based API that allows for authenticated write operations in addition to read-only ones.

It's currently missing from both the live documentation at `/api` and the prose documentation at http://anitya.readthedocs.io/en/latest/api.html

For the prose documentation, that should just be a matter of adding a new `autoflask` block for `anitya.api_v2`.

For `/api`, I'm wondering whether or not to add it at all - perhaps it would make more sense to just add a link there to the Anitya docs on RTFD? The downside of that approach is that the version of the API docs may not match the running version of Anitya (it will for release-monitoring.org, but may not for private instances).

**Comment by jeremycline** [comment]
I changed the ``/api`` endpoint to just redirect to ``docs/api.html`` within the static Flask directory and marked it as deprecated. For developers you just need to do ``make install`` on the docs, and for production deployments you just need to set up an Apache/nginx/etc. redirect so your web server handles serving the content directly rather than letting Flask doing the heavy lifting. This was in #456.

Note that the docs can't be built on RTD until #462 is merged since it's not able to install Anitya in the venv (since it requires Jinja2 and SQLAlchemy installed before you can run the setup.py).
