### ISSUE TITLE
The dateutils in production is not the same as the dateutils in the dev environment

### ISSUE THREAD

**Issue by jeremycline** [release-monitoring/anitya#476]
The specfile installs [python-dateutil](https://admin.fedoraproject.org/pkgdb/packages/python-dateutil). However, the upstream of that package is https://pypi.python.org/pypi/python-dateutil/ and our requirements file has [dateutils](https://pypi.python.org/pypi/dateutils/).

Presumably we want the one used in production, but we should also have tests that would have caught this particular problem. It may be the dependency isn't necessary at all.

- [ ] Find out if the dependency is necessary

- [ ] If it is necessary, write tests for the code that uses it

- [ ] Fix the requirements files to reference python-dateutil

**Comment by chaiku** [comment]
@jeremycline , I presume you are talking about the python-dateutil requirement in the Dockerfile. If that is the case, then I think the [python-dateutils](https://pypi.python.org/pypi/python-dateutil/ ) module and the dateutils in the requirements file refer to the same. Saying this since I tried to pip install the python-dateutils module after pip installing from the requirements file and see this message
`(fedora) [ckukde@chaitanya ~]$ pip install python-dateutil`
`Requirement already satisfied: python-dateutil in ./virtualenvs/fedora/lib/python2.7/site-packages`
`Requirement already satisfied: six>=1.5 in ./virtualenvs/fedora/lib/python2.7/site-packages (from python-dateutil)`

Let me know if I am grossly wrong here :)

**Comment by jeremycline** [comment]
I see why this is working. ``dateutils`` depends on ``python-dateutil`` (both those are the PyPI names) so even in the development environment ``python-dateutil`` is available. There's a single place this package is used, and it's the ``python-dateutil`` variety:
```
 jcline  (e) dateutil  ~  devel  fedora-infra  anitya  git grep dateutil
Dockerfile:        python-dateutil \
anitya/admin.py:from dateutil import parser
files/anitya.spec:BuildRequires:  python-dateutil
files/anitya.spec:Requires:  python-dateutil
requirements/el7-requirements.txt:python-dateutil == 1.5
requirements/readthedocs.txt:dateutils
requirements/requirements.txt:dateutils
```

The fix here should be to adjust the requirement.txt files to use ``python-dateutil`` rather than ``dateutils``.
