### ISSUE TITLE
bodhi: no upstream version found. - https://github.com/fedora-infra/bodhi/tags - class="tag-name">([^<]*)</span

### ISSUE THREAD

**Issue by bowlofeggs** [release-monitoring/anitya#511]
I released a new Bodhi about 36 hours ago, and I didn't see a BZ filed by Fedora's the-new-hotness. When I went to [Anitya](https://release-monitoring.org/project/11224/) to check it out, it had a log message:

```
bodhi: no upstream version found. - https://github.com/fedora-infra/bodhi/tags - class="tag-name">([^<]*)</span
```

**Comment by jeremycline** [comment]
I'm pretty sure this is because we don't use the GitHub API and they're (reasonably) rate-limiting us. #502 should help with the root cause of this. 

However, we also should have more helpful error messages. [Just printing out the regex we didn't find isn't enough context](https://github.com/release-monitoring/anitya/blob/2d0972bd47b6e69a50086a154ffbdbcfa218fe29/anitya/lib/backends/__init__.py#L302).

**Comment by nqb** [comment]
I get same issue for GLPI project in Anitya when owner release [9.3-beta](https://github.com/glpi-project/glpi/releases/tag/9.3-beta). Maybe linked to "pre-release" label.

**Comment by nqb** [comment]
Don't know why but issue disappeared and 9.3-beta was retrieved.

**Comment by sanjayankur31** [comment]
Dupe of #581 ?

**Comment by Zlopez** [comment]
I'm leaving this open because of the request to change the logged message.

**Comment by abitrolly** [comment]
> I'm pretty sure this is because we don't use the GitHub API and they're (reasonably) rate-limiting us.

@jeremycline`and I am pretty sure this is because GitHub changed the markup - https://web.archive.org/web/20180901104550/https://github.com/fedora-infra/bodhi/tags - doesn't contain `tag-name` anymore, and the error message is completely helpful.

**Comment by Zlopez** [comment]
Fixed by https://github.com/release-monitoring/anitya/pull/582
