### ISSUE TITLE
https://release-monitoring.org site down

### ISSUE THREAD

**Issue by glensc** [release-monitoring/anitya#519]
https://release-monitoring.org/ - This site can’t be reached

release-monitoring.org refused to connect.

Try:
- Checking the connection
- Checking the proxy and the firewall

ERR_CONNECTION_REFUSED

is the site lacking monitoring? or why it's down over 3 hours already?

**Comment by nirik** [comment]
It's down because the virthost it's on suffered not one, not two, but 3 disks failing.

The faulty disks needed to be called it and replaced, then we needed to reinstall the virthost, then the service. It's close to finished restoring from backups now and hopefully will be up in the next 30min or so. 

I will add a comment when it's fully back up. Thanks for your patience.

**Comment by nirik** [comment]
ok. Should be back up and in service, please let us know if you see any issues with it.

**Comment by pypingou** [comment]
Looks up and running for me.

Let's close and re-open if there are more problems.

Thanks @nirik  :)
