### ISSUE TITLE
query for all projects retrieves 2 projects with same name in different order

### ISSUE THREAD

**Issue by ricardo-martincoski** [release-monitoring/anitya#533]
Hello,

I am reviewing a local script to be used by Buildroot distro to generate a table listing projects, current version in Buildroot, and latest available version based on release-monitoring (and nice colors to mark projects that are up-to-date or not).
While we don't populate all the mappings for the distro, we would like to have guesses for projects without mapping.

Here is a small and clumsy script that demonstrates what I found:

```
import json
import os
import subprocess
def print_id(list):
    for i in list['projects']:
        if i['name'] == 'readline':
            print(i['id'])
API = "http://release-monitoring.org/api"
url1 = os.path.join(API, "projects", "?pattern=%s" % 'readline')
url2 = os.path.join(API, "projects")
subprocess.call(['wget', '-O', 'readline', url1])
subprocess.call(['wget', '-O', 'projects', url2])
print_id(json.load(open('readline')))
print_id(json.load(open('projects')))

```
Sometimes it gives me:
913
4173
4173
913
and sometimes it gives me:
913
4173
913
4173
It seems to not always return the same order. If I run the above script few times in a row the order is consistent. If I wait few hours the result can change.

The same occurs for zlib.

**Comment by ricardo-martincoski** [comment]
I don't really develop using flask, so forgive me if my suggestion is stupid.
Couldn't a more consistent result be achieved with a simple change like this?

```
anitya/db/models.py @ Project.all(...)
         ).order_by(
             sa.func.lower(Project.name)
+        ).order_by(
+            Project.id
         )

```
Unfortunately I am using an old distro (Ubuntu 16.04) so the setup to test this code was not quick (missing vagrant extensions).
I plan to upgrade my distro but it takes time, so it's unlikely I can try to contribute code any time soon.

**Comment by jeremycline** [comment]
Hi @ricardo-martincoski, thanks for the bug report.

Yes, ordering by id in addition to the name should produce consistent results. We're trying to retire the v1 API, though, since it has a lot of other problems (lots of endpoints don't paginate, for example). The new API doesn't appear to be ordering by anything beyond name (https://github.com/release-monitoring/anitya/blob/a0a9343dd86d9b7d41487b241f8e102d3321deee/anitya/api_v2.py#L328) so it'd probably be a good time to change that. It could order on ecosystem rather than project ID since projects should now have that set.

Feedback on the new API would be most welcome. Also, if you're interested in making a PR I'd be happy to help you with that. Anitya will also run in a Python virtualenv and it can use an SQLite database. I see I didn't write [any docs on that](https://anitya.readthedocs.io/en/latest/contributing.html#development-environment) so I can start by doing that if you need directions there.

**Comment by ricardo-martincoski** [comment]
Hi @jeremycline , thank you for your help.

Indeed, as I read on the comments in the code, ecosystem will contain the homepage for the 2 projects I mentioned. So it seems suitable to produce consistent results.

Is api_v2 already deployed to release-monitoring besides v1?
I mean: can I start using it in a script, or there will be a switch from v1 to v2 at some point and only then v2 and only v2 can be used?


Yes, I am willing to make a PR.
Now that you mention virtualenv I found its docs on README.rst, sorry I missed that.
The doc seems to need some refresh (and maybe duplicating the info to docs/contributing.rst later)
Should I open another issue about this doc? To avoid 2 discussions in the same issue?

So far I already could run tox:
```
  py27: commands succeeded
  py35: commands succeeded
ERROR:   py36: InterpreterNotFound: python3.6
ERROR:   lint: commands failed
  docs: commands succeeded
```
I will install python3.6, I found some documentation on that for my current distro.

Here some feedback on the doc:
Instead of
`pip install -r requirements/requirements.txt`
I needed to use
`pip install -r requirements.txt`

Its kind of obvious, but maybe you want also to mention to:
`pip install oidc-register`
inside the virtualenv.

For me the command to configure the local instance to authenticate gives:
```
usage: oidc-register [-h] [--token-introspection-uri TOKEN_INTROSPECTION_URI]
                     [--output-file OUTPUT_FILE] [--debug]
                     provider_url application_url redirect_uris
                     [redirect_uris ...]
oidc-register: error: too few arguments
```
Is the solution to this obvious to you?
What would be a good value for redirect_uris?

**Comment by jeremycline** [comment]
> Is api_v2 already deployed to release-monitoring besides v1?

Not quite yet, unfortunately. I hope to have it up and running in a staging instance of release-monitoring.org soon. We haven't had a staging instance previously so it's taking a while to get the infrastructure all set up.

You're right, the documentation definitely needs updating. We actually ended up not using oidc-register so I'll write refreshed contribution docs (probably tomorrow since it's a nice offline task and I've got some traveling to do). Sorry about that! If you're eager to forge ahead I recommend looking at the ansible role and the configuration files in ansible/roles/anitya-dev/files/ since that's what's used to configure the Vagrant-provisioned VM. Otherwise, just give me a day or two to update the docs.

**Comment by ricardo-martincoski** [comment]
OK, I can test the staging instance when it is up.

Instead of going with virtualenv I decided to do the correct way and take the time to update my distro. It was easier than expected. It is up.
Now I just need to install everything again... starting with git.
In a few days I guess I can create a PR.

Thank you for your support

**Comment by jeremycline** [comment]
I think #546 addressed this, thanks!
