### ISSUE TITLE
Monitoring page for Kubernetes seems to be missing release versions

### ISSUE THREAD

**Issue by lixuna** [release-monitoring/anitya#548]
Issue: On https://release-monitoring.org/project/10954/, the latest releases for Kubernetes are not appearing

## What I would expect to see: 
- Given that I am on https://release-monitoring.org/project/10954/
- When I look for the latest Kubernetes release versions 
- Then I should see a list of releases that corresponds to the releases on https://github.com/kubernetes/kubernetes/releases

**Comment by jeremycline** [comment]
Hi @lixuna,

Thanks for the report. It looks like this is because Anitya doesn't currently record all versions, just versions it considers "newer" than ones it already knows about. Since there's an alpha tagged for 1.11 it considers that newer than the stable releases and ignores those. Anitya needs to change to record _all_ versions, regardless of whether it thinks they're newer.

**Comment by abitrolly** [comment]
![image](https://user-images.githubusercontent.com/8781107/40257565-d0e7d370-5b18-11e8-87b2-b38004944215.png)

No option to ignore alpha-beta suffixes.

**Comment by Zlopez** [comment]
The anitya is now recording all versions.

There is already issue for alpha-beta suffixes - https://github.com/release-monitoring/anitya/issues/753
