### ISSUE TITLE
How to login to dev virtualenv?

### ISSUE THREAD

**Issue by abitrolly** [release-monitoring/anitya#562]
I installed `anitya` in virtualenv, but can not login with any option to add some project for testing. What to do?

**Comment by jeremycline** [comment]
You'll need to have an account with one of the identity providers. A Fedora account is easy and what I use. Github/Gitlab/Google is also available, but requires a bit more setup since they're OAuth2. It's not currently well-documented on configuring those, so you'll need to refer to the social-auth documentation if that's the direction you choose.

**Comment by abitrolly** [comment]
No identity provider seem to work with local dev instance.

**Comment by jeremycline** [comment]
Without more information I can't really help debug this. Are you using the Vagrant environment? Which identity providers have you tried? How exactly is it failing?

**Comment by Zlopez** [comment]
I recommend to use vagrant, I had it ready for development in few minutes.

**Comment by Zlopez** [comment]
@abitrolly Do you still have this issue?

**Comment by abitrolly** [comment]
Fixed by #669 I guess.
