### ISSUE TITLE
Support for multiple prefixes

### ISSUE THREAD

**Issue by Zlopez** [release-monitoring/anitya#655]
Currently the project in Anitya supports only one prefix, which should cause problems with version comparison, if the prefix is changed in project lifetime.
We should support multiple prefixes to prevent this issue.

**Comment by yarons** [comment]
I thought about maybe having a replacement rule.

If the version on GitHub is 1_2_3 I can't reliably report the version since there are no dots involved.

Same goes for other sources, even with Regex there's a problem because even if I capture the numbers then it will work if I capture 3 digits ([\d]+)_([\d]+)_([\d]+) but if there are 2: 1_3 it will not work.

**Comment by Zlopez** [comment]
This issue is about supporting multiple prefixes, which should help in the project that has more than one prefix.
The replacement rule is something I don't have clear idea how to implement. If it will be regex, than you can just use custom backend.
