### ISSUE TITLE
Pagure  backend - prefix is not working

### ISSUE THREAD

**Issue by yarons** [release-monitoring/anitya#661]
At this project:
https://release-monitoring.org/project/5523/

There was no v at the beginning, after fixing and adding v as prefix the v was added to the version title.

**Comment by Zlopez** [comment]
Yes, the version prefix is not handled correctly in currently deployed version, but this should be fixed in https://github.com/release-monitoring/anitya/pull/652

So next version of Anitya should handle the prefix correctly. Unfortunately, only one prefix is allowed per project now, but I already have issue for this https://github.com/release-monitoring/anitya/issues/655
