### ISSUE TITLE
Incorrect version checking logic ?

### ISSUE THREAD

**Issue by tpetazzoni** [release-monitoring/anitya#685]
For x2ltpd, at https://release-monitoring.org/project/5193/, it considers 1.0.4 as the latest version, even if 1.3.13 is available upstream, and 1.3.12 was detected in the past.

**Comment by yann-morin-1998** [comment]
@tpetazzoni Notice how the version there is `1.04` and not `1.0.4`, so presumably, `1.04` sorts as more recent than `1.3`, because `04` is more than `3`.

**Comment by tpetazzoni** [comment]
@yann-morin-1998 Indeed, but still it means the latest version reported by Anitya is incorrect :-/

**Comment by yann-morin-1998** [comment]
@Zlopez Not sure if sorting by date would work in this specific case,
because most are unkown for xl2tpd.

And in the general case, it would probably not work either. Consider a
project where the 1.3.x branch is still getting maintenance relases, and
the 1.4.x branch is the latest series. If 1.3.9 is relased after 1.4.9, then
1.3.9 would be considered the latest version if sorting by date, while the
real latest version is indeed 1.4.9.

**Comment by Zlopez** [comment]
Yes, but you will get notification about new release, because it will be latest.

**Comment by Zlopez** [comment]
The Date version scheme is no longer available, it caused more issues than it solved.
Fortunately I plan to add Calendar versioning and Semantic versioning in the future and this should solve your problem.

**Comment by Zlopez** [comment]
Calendar and semantic versioning is now available in 0.17.0.
