### ISSUE TITLE
Mishandling some Gitlab URL

### ISSUE THREAD

**Issue by eclipseo** [release-monitoring/anitya#763]
Some Gitlab have more than repo/project parameters.
For example:
https://gitlab.gnome.org/World/OpenPaperwork/pyocr

and everything under:
https://gitlab.gnome.org/World/OpenPaperwork/

These are not handled by the current Gitlab backend.

**Comment by Zlopez** [comment]
I'm using the GitLab APIv4 for GitLab backend, so I need to check, how I can access these subrepositories. 

Thanks for noticing this. I didn't knew there are some projects like this.

**Comment by Zlopez** [comment]
## Implementation details
This should be easy to fix. Instead of reading specific token, we should read all the remaining tokens in URL. See https://github.com/release-monitoring/anitya/blob/master/anitya/lib/backends/gitlab.py#L89

The tokens in `repo` key should be split by `%%2F`.

**Comment by nphilipp** [comment]
I played around with this a little and it looks as if isn't always that easy.

At least in this specific case, i.e. GNOME's self-hosted GitLab instance, if an intermediate HTTP proxy decodes the `%2F`-encoded slashes, the resulting URL will become something like `https://gitlab.domain.tld/api/v4/groups/GroupName/SubgroupName` instead of `...GroupName%2FSubgroupName`, resulting in e.g. this:

````
nils@gibraltar:~> http get 'https://gitlab.gnome.org/api/v4/groups/World%2FOpenPaperwork'
HTTP/1.1 404 Not Found
Cache-Control: no-cache
Connection: close
Content-Length: 33
Content-Type: application/json
Date: Tue, 10 Dec 2019 12:35:30 GMT
Server: Apache/2.4.6 (Red Hat Enterprise Linux)
Strict-Transport-Security: max-age=15768000;includeSubdomains
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: Fvx8we3AQy2
X-Runtime: 0.033270

{
    "message": "404 Group Not Found"
}

nils@gibraltar:~>
````

As I understand it, accessing the subgroup or one of its project at one endpoint is necessary in the context of Anitya backends because `get_version_url()` is expected to return a URL where we can check for changes.

I've found a workaround that works on the command line, but it involves searching the project by name in the whole group (i.e. `World`) and then filtering the results, so I don't think it works here without substantially changing the code, i.e. catering for backends that can't compute a direct API URL.

**Comment by nphilipp** [comment]
For reference:

* Upstream GitLab issue "Unable to access subgroup using its path through API": https://gitlab.com/gitlab-org/gitlab-foss/issues/29296#note_83325303
* Configuration snippets for various web servers: https://gitlab.com/gitlab-org/gitlab-recipes/tree/master/web-server

**Comment by nphilipp** [comment]
Filed an issue with GNOME infrastructure here: https://gitlab.gnome.org/Infrastructure/GitLab/issues/423

**Comment by nphilipp** [comment]
...and it's fixed! @Zlopez, do you want to put this on the 0.18.0 milestone again?

**Comment by Zlopez** [comment]
I want to release 0.18.0 as soon as possible, so if you create the PR soon, it will be part of the release.
