### ISSUE TITLE
No reporting for some of my packages, especially py4j

### ISSUE THREAD

**Issue by rapgro** [release-monitoring/anitya#770]
There's no new rhbz for py4j since months although upstream released two versions.
In assumption I don't get any reports for other packages, too.

**Comment by rapgro** [comment]
Is that due to subpackages with empty/non-exist main package, as we normally do for python packaging to comply with our guidelines?

**Comment by rapgro** [comment]
Project: py4j (PyPi) is wrongly mapped to "Fedrora" (no idea what distro, mind the typo?)

**Comment by rapgro** [comment]
https://github.com/release-monitoring/anitya/issues/772

**Comment by Zlopez** [comment]
I refreshed the project https://release-monitoring.org/project/6493/ and the bug was filled correctly https://bugzilla.redhat.com/show_bug.cgi?id=1701163
I noticed, that the one you are mentioning is actually duplicate to the one I refreshed - https://release-monitoring.org/project/6492/
There is also another duplicate added from sourceforge - https://release-monitoring.org/project/6469/

I will remove the duplicates and leave only the one with correct mapping.

**Comment by Zlopez** [comment]
There is now only one project py4j instead of three projects - https://release-monitoring.org/project/6493/

**Comment by Zlopez** [comment]
Closing this issue as solved

**Comment by rapgro** [comment]
No idea what's the correct upstream as backend to track. GitHub seems to be the best actually. We'd reconfigure if another backend is better (SourceForge or PyPI). Thanks.
